---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  annotations:
    container.apparmor.security.beta.kubernetes.io/redis-commander: runtime/default
    container.security.alpha.kubernetes.io/redis-commander: runtime/default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-comnander
  template:
    metadata:
      labels:
        app: redis-comnander
        tier: backend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: redis-commander
          image: redis
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis-comnander
              containerPort: 6379
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
