---
apiVersion: v1
kind: Service
metadata:
  name: redis-commander
  labels:
    app: redis-comnander
    tier: backend
spec:
  ports:
    - port: 6379
      targetPort: redis
      name: redis
  selector:
    app: redis
    tier: backend
